[[envs]]
key = "DEV_DRIVE_LETTER"
value = "D:"

[[envs]]
key = "DEV_TOOLS_PATH"
value = "$(DEV_DRIVE_LETTER)\\win\\dev-tools"

[[envs]]
key = "DEV_PROGRAM_PATH"
value = "$(DEV_DRIVE_LETTER)\\win\\program"

[[envs]]
key = "DEV_TOOLS_CLIBS_PATH"
value = "$(DEV_DRIVE_LETTER)\\win\\dev-tools\\clibs"

[[envs]]
key = "XDG_CONFIG_HOME"
value = "$(DEV_TOOLS_PATH)\\neovim\\config"

[[envs]]
key = "XDG_DATA_HOME"
value = "$(DEV_TOOLS_PATH)\\neovim\\data"

[[envs]]
key = "XDG_CACHE_HOME"
value = "$(DEV_TOOLS_PATH)\\cache"

[[envs]]
key = "INCLUDE"
value = [
   "$(DEV_DRIVE_LETTER)\\win\\dev-tools\\microsoft-build-tools\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\include",
  "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.26100.0\\ucrt"
]

[[envs]]
key = "LIB"
value = [
  "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64",
  "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64",
  "$(DEV_TOOLS_PATH)\\microsoft-build-tools\\BuildTools\\VC\\Tools\\MSVC\\14.43.34808\\lib\\x64",
]

[[envs]]
key = "LIBPATH"
value = [
  "$(DEV_TOOLS_PATH)\\vcpkg-master\\installed\\x64-windows\\lib",
  "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64",
  "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64",
  "$(DEV_DRIVE_LETTER)\\win\\dev-tools\\microsoft-build-tools\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\lib\\x64"
]

[[envs]]
key = "PATH"
value = [
    # Default paths
    "C:\\Windows\\System32\\",
    "C:\\Windows\\SysWOW64\\",
    "C:\\WINDOWS",
    "C:\\WINDOWS\\System32\\Wbem",
    "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0",
    "C:\\WINDOWS\\System32\\OpenSSH",
    "C:\\Program Files\\OpenSSL-Win64\\bin",
    "C:\\Program Files\\MySQL\\MySQL Server 8.3\\bin",
    "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64",
    "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64",
    # Devtools and TestPath etc.
    "$(DEV_TOOLS_PATH)\\neovim\\app\\bin",
     "$(DEV_TOOLS_PATH)\\git\\Git\\bin",
   "$(USERPROFILE)\\AppData\\Local\\Microsoft\\WindowsApps",
]

