[[envs]]
key = "JAVA_HOME"
value = "$(DEV_TOOLS_PATH)\\android\\android-studio\\jbr"

[[envs]]
key = "ANDROID_NDK_HOME"
value = "$(DEV_TOOLS_PATH)\\android\\sdk\\ndk\\27.0.12077973"

[[envs]]
key = "PYENV_ROOT"
value = "$(DEV_TOOLS_PATH)\\python\\pyenv"

[[envs]]
key = "PYENV"
value = "$(DEV_TOOLS_PATH)\\python\\pyenv\\pyenv-win"

[[envs]]
key = "PYENV_HOME"
value = "$(DEV_TOOLS_PATH)\\python\\pyenv\\pyenv-win"

[[envs]]
key = "GOPATH"
value = "$(DEV_TOOLS_PATH)\\go\\go-path"


[[envs]]
key = "PATH"
value = [
    # Default paths
    "C:\\Windows\\System32\\",
    "C:\\Windows\\SysWOW64\\",
    "C:\\WINDOWS",
    "C:\\WINDOWS\\System32\\Wbem",
    "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0",
    "C:\\WINDOWS\\System32\\OpenSSH",
    "C:\\Program Files\\OpenSSL-Win64\\bin",
    "C:\\Program Files\\MySQL\\MySQL Server 8.3\\bin",
    "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64",
    "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64",
    # Devtools and TestPath etc.
    "$(DEV_TOOLS_PATH)\\neovim\\app\\bin",
    "$(USERPROFILE)\\use-bin\\git\\CLI",
   "$(DEV_TOOLS_PATH)\\nodejs\\bin\\",
   "$(DEV_TOOLS_PATH)\\git\\Git\\bin",
   "$(USERPROFILE)\\AppData\\Local\\Microsoft\\WindowsApps",
   
   "$(DEV_TOOLS_PATH)\\mpv",
   "$(DEV_TOOLS_PATH)\\x86_64-15.1.0-release-posix-seh-ucrt-rt_v12-rev0\\mingw64\\bin",
    "$(DEV_TOOLS_PATH)\\microsoft-build-tools\\BuildTools\\VC\\Tools\\MSVC\\14.43.34808\\bin\\Hostx64\\x64",
    "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.26100.0\\x64",
    #"$(DEV_TOOLS_PATH)\\pspsdk\\bin\\",
    #"$(DEV_TOOLS_PATH)\\pspsdk\\psp\\bin\\",
   "$(DEV_TOOLS_PATH)\\go\\bin\\",
    "$(DEV_TOOLS_PATH)\\go\\go-path\\bin",
       "$(DEV_TOOLS_PATH)\\ffmpeg-2024-11-03-git-df00705e00-full_build\\bin\\",
     "$(DEV_TOOLS_PATH)\\jq\\",
    "$(DEV_TOOLS_PATH)\\tinygo0.37.0.windows-amd64\\tinygo\\bin",
   ]

