[[configs]]
description = "Full Integration Test (TOML)"

[[envs]]
APP_NAME = "eec-toml-core"

[[envs]]
APP_ROOT = "D:\\work\\${APP_NAME}"

[[envs]]
HOST_NAME = "$(hostname)"

[[envs]]
APP_SUMMARY = "Host:${HOST_NAME}_Name:${APP_NAME}_OS:$(echo %OS% || uname)"

[[envs]]
PATH = [
  "${APP_ROOT}\\exec",
  "C:\\external\\tools"
]

[program]
path = "cmd"
args = ["/c", "set APP_ && echo %PATH%"]
